### ISSUE TITLE
Mention joining user

### ISSUE THREAD

**Issue by sefsh** [williamkray/maubot-welcome#1]
Would be nice for the bot to mention the user in the welcome message: `Welcome #user:domain.tld! Please…`

**Comment by williamkray** [comment]
it definitely would! i was going to try to implement that, and then didn't want to get lost in the weeds with variable substitution and proper quoting syntax super late at night, but it is something i can add in at some point.

**Comment by ghost** [comment]
Bump! I also want to be able to mention the user who joined

**Comment by williamkray** [comment]
closed with https://github.com/williamkray/maubot-welcome/commit/4f00f9017f5b98aeeaad8f0a03c8ade837eae278

thanks for the reminder

**Comment by ghost** [comment]
Thank you
