### ISSUE TITLE
Ability to set a different message per room

### ISSUE THREAD

**Issue by dannycolin** [williamkray/maubot-welcome#2]
In a larger community with multiple rooms, it'd be useful to have the ability to set a different message for each rooms monitored by the bot.

**Comment by williamkray** [comment]
I actually initially tried to do this when first writing the bot, but it adds significant complexity to the code (needing to map each room to a message) and can easily be implemented by just configuring multiple instances of the plugin.

I will happily review and PRs that accomplish this but will not spend any more effort on it myself. I'll leave this issue open in case someone wants to tackle it.

**Comment by ghost** [comment]
> can easily be implemented by just configuring multiple instances of the plugin.

Yes, but what should someone do it then bot runs in standalone mode?

**Comment by williamkray** [comment]
> > can easily be implemented by just configuring multiple instances of the plugin.
> 
> Yes, but what should someone do it then bot runs in standalone mode?

i leave that as an exercise for the user. as it is written, this plugin obviously does not support complex configuration in standalone mode. 

i imagine you could run multiple standalone instances side-by-side that authenticate as the same maubot user. or, you could fork this repository and submit a PR that accomplishes this functionality :smile:

**Comment by williamkray** [comment]
unarchiving this repo temporarily just to update this issue: this functionality is rolled into https://github.com/williamkray/maubot-communitybot which supersedes this plugin. thanks folks.
